In [2]:
import numpy as np

In [3]:
arr1 = np.array([10,20,30,40,50])
print(arr1)

[10 20 30 40 50]


In [ ]:
#indexing
print(arr1[1])
print(arr1[-2])

20
40


In [7]:
arr2 = np.array([[11,22,33],[44,55,66]])
print(arr2)

[[11 22 33]
 [44 55 66]]


In [9]:
print(arr2[0])
print(arr2[1][1])

[11 22 33]
55


In [10]:
print(arr2[0,1])

22


In [12]:
arr2 = np.array([[11,22,33],[44,55,66],[77,88,99],[1,2,3]])
print(arr2)

[[11 22 33]
 [44 55 66]
 [77 88 99]
 [ 1  2  3]]


In [17]:
#slicing
arr1 = np.array([11,22,33,44,55])
print(arr1)
print(arr1[-2])
print(arr1[1:-1:1])
print(arr1[-1:-4:-1])

[11 22 33 44 55]
44
[22 33 44]
[55 44 33]
