In [3]:
import numpy as np

In [ ]:
aa1 = np.array([11,22,33,44])
aa2 = np.array([66,77,88,99])
print(aa1)
print(aa2)

[11 22 33 44]
[66 77 88 99]


In [ ]:
vs = np.vstack((aa1,aa2))
print(vs)

[[11 22 33 44]
 [66 77 88 99]]


In [ ]:
hs = np.hstack((aa1,aa2))
print(hs)

[11 22 33 44 66 77 88 99]


In [ ]:
a2 = np.array([[1,2,3,4],[5,6,7,8]])
print(a2)

[[1 2 3 4]
 [5 6 7 8]]


In [9]:
aa1 = a2.flatten()
print(aa1)

[1 2 3 4 5 6 7 8]


In [10]:
aa2 = a2.ravel()
print(aa2)

[1 2 3 4 5 6 7 8]


In [11]:
aa1[2] = 999
print(aa1)
print(a2)

[  1   2 999   4   5   6   7   8]
[[1 2 3 4]
 [5 6 7 8]]


In [12]:
aa2[2] = 999
print(aa2)
print(a2)

[  1   2 999   4   5   6   7   8]
[[  1   2 999   4]
 [  5   6   7   8]]


In [4]:
c = np.array([1,2,3,4])
aa1_copy = c.copy()
print(c)
print(aa1_copy)

[1 2 3 4]
[1 2 3 4]


In [5]:
c_view = c.view()
print(c)
print(c_view)

[1 2 3 4]
[1 2 3 4]


In [6]:
c_copy = aa1_copy[0] = 1111
print(c)
print(aa1_copy)

[1 2 3 4]
[1111    2    3    4]


In [10]:
view_arr = c.view()
view_arr[0] = 100
print(c)
print(view_arr)

[100   2   3   4]
[100   2   3   4]


In [17]:
arr = np.array([11,33,55,66,22,44])
arr.sort()
print(arr)

[11 22 33 44 55 66]


In [11]:
number = np.array([11,22,33,44,55,66,77,88,99,100])
result = np.where(number>55)
print(result)

(array([5, 6, 7, 8, 9]),)


In [12]:
marks = np.array([44,56,78,90,12,34])
result = np.where(marks>40,"pass","fail")
print(result)

['pass' 'pass' 'pass' 'pass' 'fail' 'fail']


In [31]:
numbers = np.array([1,2,3,4,5,6,7,8,9,10])
result = np.where(numbers%2==0,"even","odd")
print(result)

['odd' 'even' 'odd' 'even' 'odd' 'even' 'odd' 'even' 'odd' 'even']


In [27]:
numbers = np.array([1,2,3,4,5,6,7,8,9,10])
result = np.append(numbers,78)
print(result)

[ 1  2  3  4  5  6  7  8  9 10 78]


In [28]:
result = np.insert(numbers,2,999)
print(result)

[  1   2 999   3   4   5   6   7   8   9  10]


In [29]:
result = np.delete(numbers,3)
print(result)

[ 1  2  3  5  6  7  8  9 10]


In [30]:
result = np.split(numbers,5)
print(result)

[array([1, 2]), array([3, 4]), array([5, 6]), array([7, 8]), array([ 9, 10])]
